# Generated by Django 5.0.4 on 2024-05-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsysteme',
            name='filiale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.filiale'),
            preserve_default=False,
        ),
    ]
