# Generated by Django 5.0.4 on 2024-06-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_etatsysteme_filiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveur',
            name='statut',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='adresse',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='filiale',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.filiale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serveur',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='unite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
