# Generated by Django 5.0.4 on 2024-06-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_serveur_statut_alter_serveur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveur',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='filiale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serveurs', to='myapp.filiale'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='statut',
            field=models.CharField(default='non spécifié', max_length=100),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='unite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.filiale')),
            ],
        ),
    ]
