# Generated by Django 5.0.4 on 2024-07-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_serveur_adresse_alter_serveur_filiale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clear_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='nomserveur',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
